from animtools import spin
from . import horizontalbarbuilder
from horizontalbarbuilder import HorizontalBarBuilder

horizontal_bars = [
        HorizontalBarBuilder(),
        HorizontalBarBuilder(fill_symbol="/", empty_symbol=" "),
        HorizontalBarBuilder(fill_symbol="/", empty_symbol="-"),
        HorizontalBarBuilder(fill_symbol="█", empty_symbol=" ", formatting="{fill}{space} {progress}%"),
        HorizontalBarBuilder(fill_symbol="█", empty_symbol="▒", formatting="{fill}{space} {progress}%"),
        HorizontalBarBuilder(fill_symbol="▐", empty_symbol=" ", formatting="{fill}{space} {progress}%"),
        HorizontalBarBuilder(fill_symbol="▐", empty_symbol="▒", formatting="{fill}{space} {progress}%"),
        HorizontalBarBuilder(fill_symbol="<", empty_symbol="-", formatting="[{space}{fill}] {progress}% (Reverse c:)"),
    ]
    
animations =  [
        ["(O w O) {0}",
        "(ow O ) {0}",
        "(w O  ) {0}",
        "(wO   ) {0}",
        "(o    ) {0}",
        "(     ) {0}",
        "(    -) {0}",
        "(   - ) {0}",
        "(  -  ) {0}",
        "( -   ) {0}",
        "(-    ) {0}",
        "(     ) {0}",
        "(    o) {0}",
        "(   Ow) {0}",
        "(  O w) {0}",
        "( O w ) {0}"],

        ["["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", 0*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -1*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -2*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -3*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -4*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -5*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -6*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -7*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -8*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -9*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -10*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -11*2)+"] {0}",
        "["+spin("▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▇ ▆ ▅ ▄ ▃ ", -12*2)+"] {0}"],

        ["[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", 0) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -1) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -2) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -3) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -4) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -5) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -6) + "] {0}",
        "[" + spin("⠁⠂⠄⡀⢀⠠⠐⠈", -7) + "] {0}"],
        
        ["[▁ ▁ ▁] {0}",
        "[▂ ▁ ▁] {0}",
        "[▃ ▁ ▁] {0}",
        "[▄ ▁ ▁] {0}",
        "[▅ ▁ ▁] {0}",
        "[▆ ▁ ▁] {0}",
        "[▇ ▁ ▁] {0}",
        "[█ ▁ ▁] {0}",
        "[▇ ▁ ▁] {0}",
        "[▆ ▁ ▁] {0}",
        "[▅ ▁ ▁] {0}",
        "[▄ ▁ ▁] {0}",
        "[▃ ▁ ▁] {0}",
        "[▂ ▁ ▁] {0}",
        "[▁ ▁ ▁] {0}",
        "[▁ ▂ ▁] {0}",
        "[▁ ▃ ▁] {0}",
        "[▁ ▄ ▁] {0}",
        "[▁ ▅ ▁] {0}",
        "[▁ ▆ ▁] {0}",
        "[▁ ▇ ▁] {0}",
        "[▁ █ ▁] {0}",
        "[▁ ▇ ▁] {0}",
        "[▁ ▆ ▁] {0}",
        "[▁ ▅ ▁] {0}",
        "[▁ ▄ ▁] {0}",
        "[▁ ▃ ▁] {0}",
        "[▁ ▂ ▁] {0}",
        "[▁ ▁ ▁] {0}",
        "[▁ ▁ ▂] {0}",
        "[▁ ▁ ▃] {0}",
        "[▁ ▁ ▄] {0}",
        "[▁ ▁ ▅] {0}",
        "[▁ ▁ ▆] {0}",
        "[▁ ▁ ▇] {0}",
        "[▁ ▁ █] {0}",
        "[▁ ▁ ▇] {0}",
        "[▁ ▁ ▆] {0}",
        "[▁ ▁ ▅] {0}",
        "[▁ ▁ ▄] {0}",
        "[▁ ▁ ▃] {0}",
        "[▁ ▁ ▂] {0}"]
    ]